/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class slika_BMP */

#ifndef _Included_slika_BMP
#define _Included_slika_BMP
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     slika_BMP
 * Method:    writeBMPHeader
 * Signature: (IILjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_slika_BMP_writeBMPHeader
  (JNIEnv *, jobject, jint, jint, jstring);

#ifdef __cplusplus
}
#endif
#endif
