/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class slika_PAM */

#ifndef _Included_slika_PAM
#define _Included_slika_PAM
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     slika_PAM
 * Method:    convertPAMtoBMP
 * Signature: (Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_slika_PAM_convertPAMtoBMP
  (JNIEnv *, jobject, jstring, jstring);

/*
 * Class:     slika_PAM
 * Method:    convertBMPtoPAM
 * Signature: (Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_slika_PAM_convertBMPtoPAM
  (JNIEnv *, jobject, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
