/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class slika_Image */

#ifndef _Included_slika_Image
#define _Included_slika_Image
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     slika_Image
 * Method:    loadImageXML
 * Signature: (Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_slika_Image_loadImageXML
  (JNIEnv *, jobject, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
